apiVersion: v1
items:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: syndesis
    name: syndesises.syndesis.io
  spec:
    additionalPrinterColumns:
    - JSONPath: .status.phase
      description: The syndesis phase
      name: Phase
      type: string
    - JSONPath: .status.version
      description: The syndesis version
      name: Version
      type: string
    group: syndesis.io
    names:
      kind: Syndesis
      listKind: SyndesisList
      plural: syndesises
      singular: syndesis
    scope: Namespaced
    version: v1alpha1
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    labels:
      app: syndesis
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
      syndesis.io/app: syndesis
      syndesis.io/component: syndesis-operator
      syndesis.io/type: operator
    name: syndesis-extra-permissions
  rules:
  - apiGroups:
    - syndesis.io
    resources:
    - '*'
    - '*/*'
    verbs:
    - '*'
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    - build.openshift.io
    - apps.openshift.io
    - image.openshift.io
    - rbac.authorization.k8s.io
    - template.openshift.io
    - authorization.openshift.io
    - route.openshift.io
    - monitoring.coreos.com
    - integreatly.org
    resources:
    - buildconfigs
    - buildconfigs/instantiatebinary
    - buildconfigs/webhooks
    - builds
    - builds/details
    - builds/log
    - configmaps
    - endpoints
    - persistentvolumeclaims
    - pods
    - replicationcontrollers
    - replicationcontrollers/scale
    - replicationcontrollers/status
    - secrets
    - serviceaccounts
    - services
    - deploymentconfigs
    - deploymentconfigs/scale
    - deploymentconfigrollbacks
    - deploymentconfigs/instantiate
    - deploymentconfigs/rollback
    - imagestreams
    - imagestreamimages
    - imagestreammappings
    - imagestreams/secrets
    - imagestreamtags
    - roles
    - rolebindings
    - processedtemplates
    - templateconfigs
    - templateinstances
    - templates
    - rolebindings
    - routes
    - routes/custom-host
    - alertmanagers
    - prometheuses
    - servicemonitors
    - prometheusrules
    - grafanadashboards
    verbs:
    - '*'
  - apiGroups:
    - camel.apache.org
    resources:
    - '*'
    verbs:
    - '*'
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: camel-k
    name: integrationplatforms.camel.apache.org
  spec:
    additionalPrinterColumns:
    - JSONPath: .status.phase
      description: The IntegrationPlatform phase
      name: Phase
      type: string
    group: camel.apache.org
    names:
      kind: IntegrationPlatform
      listKind: IntegrationPlatformList
      plural: integrationplatforms
      shortNames:
      - ip
      singular: integrationplatform
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: camel-k
    name: integrationkits.camel.apache.org
  spec:
    additionalPrinterColumns:
    - JSONPath: .status.phase
      description: The IntegrationKit phase
      name: Phase
      type: string
    - JSONPath: .metadata.labels.camel\.apache\.org\/kit\.type
      description: The IntegrationKit type
      name: Type
      type: string
    - JSONPath: .status.image
      description: The IntegrationKit image
      name: Image
      type: string
    group: camel.apache.org
    names:
      kind: IntegrationKit
      listKind: IntegrationKitList
      plural: integrationkits
      shortNames:
      - ik
      singular: integrationkit
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: camel-k
    name: integrations.camel.apache.org
  spec:
    additionalPrinterColumns:
    - JSONPath: .status.phase
      description: The Integration phase
      name: Phase
      type: string
    - JSONPath: .status.kit
      description: The IntegrationKit to use
      name: Kit
      type: string
    group: camel.apache.org
    names:
      kind: Integration
      listKind: IntegrationList
      plural: integrations
      shortNames:
      - it
      singular: integration
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: camel-k
    name: camelcatalogs.camel.apache.org
  spec:
    additionalPrinterColumns:
    - JSONPath: .spec.version
      description: The Catalog version
      name: Version
      type: string
    group: camel.apache.org
    names:
      kind: CamelCatalog
      listKind: CamelCatalogList
      plural: camelcatalogs
      shortNames:
      - cc
      singular: camelcatalog
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: camel-k
    name: builds.camel.apache.org
  spec:
    additionalPrinterColumns:
    - JSONPath: .status.phase
      description: The build phase
      name: Phase
      type: string
    - JSONPath: .status.startedAt
      description: The time at which the build was last (re-)started
      name: Age
      type: date
    - JSONPath: .status.duration
      description: The build last execution duration
      name: Duration
      type: string
    - JSONPath: .status.failure.recovery.attempt
      description: The number of execution attempts
      name: Attempts
      type: integer
    group: camel.apache.org
    names:
      kind: Build
      listKind: BuildList
      plural: builds
      singular: build
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    labels:
      app: camel-k
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
    name: camel-k:edit
  rules:
  - apiGroups:
    - camel.apache.org
    resources:
    - '*'
    verbs:
    - '*'
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      app: syndesis
      syndesis.io/app: syndesis
      syndesis.io/component: syndesis-operator
      syndesis.io/type: operator
    name: syndesis-operator
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - configmaps
    - secrets
    - serviceaccounts
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
  - apiGroups:
    - ""
    resources:
    - replicationcontrollers
    - replicationcontrollers/scale
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - apps
    resources:
    - daemonsets
    - deployments
    - deployments/scale
    - replicasets
    - replicasets/scale
    - statefulsets
    - statefulsets/scale
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - extensions
    resources:
    - daemonsets
    - deployments
    - deployments/scale
    - ingresses
    - networkpolicies
    - replicasets
    - replicasets/scale
    - replicationcontrollers/scale
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - ""
    resources:
    - bindings
    - events
    - limitranges
    - namespaces/status
    - pods/log
    - pods/status
    - replicationcontrollers/status
    - resourcequotas
    - resourcequotas/status
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    - build.openshift.io
    resources:
    - buildconfigs
    - buildconfigs/webhooks
    - builds
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - ""
    - build.openshift.io
    resources:
    - buildconfigs/instantiate
    - buildconfigs/instantiatebinary
    - builds/clone
    verbs:
    - create
  - apiGroups:
    - ""
    - build.openshift.io
    resources:
    - builds/details
    verbs:
    - update
  - apiGroups:
    - ""
    - build.openshift.io
    resources:
    - builds/log
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    - apps.openshift.io
    resources:
    - deploymentconfigs
    - deploymentconfigs/scale
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - ""
    - apps.openshift.io
    resources:
    - deploymentconfigrollbacks
    - deploymentconfigs/instantiate
    - deploymentconfigs/rollback
    verbs:
    - create
  - apiGroups:
    - ""
    - apps.openshift.io
    resources:
    - deploymentconfigs/log
    - deploymentconfigs/status
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    - image.openshift.io
    resources:
    - imagestreams
    - imagestreamimages
    - imagestreammappings
    - imagestreams/secrets
    - imagestreamtags
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - ""
    - image.openshift.io
    resources:
    - imagestreamimports
    verbs:
    - create
  - apiGroups:
    - ""
    - image.openshift.io
    resources:
    - imagestreams/status
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - route.openshift.io
    resources:
    - routes
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - ""
    - template.openshift.io
    resources:
    - processedtemplates
    - templateconfigs
    - templateinstances
    - templates
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - ""
    - build.openshift.io
    resources:
    - buildlogs
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - syndesis.io
    resources:
    - '*'
    - '*/finalizers'
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - configmaps
    - secrets
    - serviceaccounts
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
  - apiGroups:
    - ""
    resources:
    - pods/log
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - replicationcontrollers
    - replicationcontrollers/scale
    - replicationcontrollers/status
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
  - apiGroups:
    - ""
    - build.openshift.io
    resources:
    - builds
    - buildconfigs
    - builds/details
    - buildconfigs/webhooks
    - buildconfigs/instantiatebinary
    - builds/log
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
  - apiGroups:
    - ""
    - apps.openshift.io
    resources:
    - deploymentconfigs
    - deploymentconfigs/scale
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - ""
    - apps.openshift.io
    resources:
    - deploymentconfigrollbacks
    - deploymentconfigs/instantiate
    - deploymentconfigs/rollback
    verbs:
    - create
  - apiGroups:
    - ""
    - apps.openshift.io
    resources:
    - deploymentconfigs/log
    - deploymentconfigs/status
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    - image.openshift.io
    resources:
    - imagestreams
    - imagestreamimages
    - imagestreammappings
    - imagestreams/secrets
    - imagestreamtags
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - ""
    - image.openshift.io
    resources:
    - imagestreams/status
    - imagestreamimports
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - get
    - list
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - roles
    - rolebindings
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
  - apiGroups:
    - ""
    - template.openshift.io
    resources:
    - processedtemplates
    - templateconfigs
    - templateinstances
    - templates
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - authorization.openshift.io
    resources:
    - rolebindings
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
  - apiGroups:
    - route.openshift.io
    resources:
    - routes
    - routes/custom-host
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
    - patch
  - apiGroups:
    - camel.apache.org
    resources:
    - '*'
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - alertmanagers
    - prometheuses
    - servicemonitors
    - prometheusrules
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
  - apiGroups:
    - integreatly.org
    resources:
    - grafanadashboards
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
    - watch
  - apiGroups:
    - serving.knative.dev
    resources:
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - eventing.knative.dev
    resources:
    - channels
    verbs:
    - get
    - list
    - watch
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: syndesis
      syndesis.io/app: syndesis
      syndesis.io/component: syndesis-operator
      syndesis.io/type: operator
    name: syndesis-operator
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    labels:
      app: syndesis
      syndesis.io/app: syndesis
      syndesis.io/component: syndesis-operator
      syndesis.io/type: operator
    name: syndesis-operator:install
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: syndesis-operator
  subjects:
  - kind: ServiceAccount
    name: syndesis-operator
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: syndesis
      syndesis.io/app: syndesis
      syndesis.io/component: syndesis-operator
      syndesis.io/type: operator
    name: syndesis-operator
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/syndesis/syndesis-operator:latest
      importPolicy:
        scheduled: true
      name: latest
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: syndesis
      syndesis.io/app: syndesis
      syndesis.io/component: syndesis-operator
      syndesis.io/type: operator
    name: syndesis-operator
  spec:
    replicas: 1
    selector:
      syndesis.io/app: syndesis
      syndesis.io/component: syndesis-operator
      syndesis.io/type: operator
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          syndesis.io/app: syndesis
          syndesis.io/component: syndesis-operator
          syndesis.io/type: operator
      spec:
        containers:
        - env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: syndesis-operator
          image: ' '
          imagePullPolicy: IfNotPresent
          name: syndesis-operator
          ports:
          - containerPort: 60000
            name: metrics
        serviceAccountName: syndesis-operator
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - syndesis-operator
        from:
          kind: ImageStreamTag
          name: syndesis-operator:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: syndesis.io/v1alpha1
  kind: Syndesis
  metadata:
    name: app
  spec:
    devSupport: false
kind: List
