apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Seamless Upgrades
    categories: Integration & Delivery
    certified: "false"
    containerImage: syndesis/syndesis-operator:latest
    description: Manages the installation of Syndesis, a flexible and customizable open source platform that provides core integration capabilities as a service.
    operators.operatorframework.io/builder: operator-sdk-v1.0.5
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
    repository: https://github.com/syndesisio/syndesis/
    support: Syndesis
  name: syndesis-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Syndesis is the Schema for the syndeses API
      displayName: Syndesis
      kind: Syndesis
      name: syndesises.syndesis.io
      resources:
      - kind: Subscription
        name: jaeger-product
        version: operators.coreos.com/v1alpha1
      - kind: ClusterRole
        name: syndesis-auth-delegator
        version: rbac.authorization.k8s.io/v1
      - kind: Secret
        name: syndesis-global-config
        version: v1
      - kind: ClusterRole
        name: syndesis-operator
        version: rbac.authorization.k8s.io/v1
      - kind: Deployment
        name: syndesis-operator
        version: apps/v1
      - kind: Role
        name: syndesis-operator
        version: rbac.authorization.k8s.io/v1
      - kind: ServiceAccount
        name: syndesis-operator
        version: v1
      - kind: ClusterRole
        name: syndesis-operator-cluster-role-bindings
        version: rbac.authorization.k8s.io/v1
      - kind: ClusterRole
        name: syndesis-server-kafka
        version: rbac.authorization.k8s.io/v1
      version: v1beta2
  description: |
    ### Syndesis operator
    Syndesis is a flexible and customizable, open source platform that provides core integration capabilities as a service.

    This operator installs as well as configures the following syndesis components:
    - syndesis-server
    - syndesis-meta
    - syndesis-ui
    - syndesis-db
    - syndesis-prometheus
    - syndesis-proxy
    - syndesis-oauthproxy

    ### How to install
    When the operator is installed (you have created a subscription and the operator is running in the selected namespace) create a new CR of Kind Syndesis (click the Create New button). The CR spec contains all defaults (see below).

    ### CR Defaults
    The CR definition is pretty simple and an empy CR will trigger a base installation.

    Within the addons section, users are able to enable specific addons. The available addons at the moment are:
    - jaeger: enable jaeger
    - ops: enables monitoring, requires extra CRDs
    - todo: a simple todo application

    To enable addons, set "addon_name": {"enabled": true} in the CR.
  displayName: Syndesis Operator
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMDt9LmNscy0ye2ZpbGw6I2MyMWEwMDt9LmNscy0ze2ZpbGw6I2ZmZjt9LmNscy00e2ZpbGw6I2VhZWFlYTt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPnByb2R1Y3RpY29uc18xMDE3X1JHQl9JbnRlZ3JhdGlvbiBmaW5hbCBjb2xvcjwvdGl0bGU+PGcgaWQ9IkxheWVyXzEiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PGNpcmNsZSBjbGFzcz0iY2xzLTEiIGN4PSI1MCIgY3k9IjUwIiByPSI1MCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTIwLjcxIDUwKSByb3RhdGUoLTQ1KSIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTg1LjM2LDE0LjY0QTUwLDUwLDAsMCwxLDE0LjY0LDg1LjM2WiIvPjxwYXRoIGQ9Ik0zMSwzMS4zNmExLjk0LDEuOTQsMCwwLDEtMy42Mi0uODkuNDMuNDMsMCwwLDEsLjUzLS40NCwzLjMyLDMuMzIsMCwwLDAsMi44MS43QS40My40MywwLDAsMSwzMSwzMS4zNloiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik03Ny42Myw0NC43NkM3Ny4xMiw0MS4zNCw3MywyMSw2Ni4zMiwyMWMtMi40NCwwLTQuNTksMy4zNS02LDYuODgtLjQ0LDEuMDYtMS4yMywxLjA4LTEuNjMsMEM1Ny4yNCwyNC4xNiw1NS44OCwyMSw1My4yOCwyMSw0My4zNCwyMSw0Ny44NCw0NS4xOCwzOSw0NS4xOGMtNC41NywwLTUuMzctMTAuNTktNS41LTE0LjcyLDIuMTkuNjUsMy4zLTEsMy41NS0yLjYxYS42My42MywwLDAsMC0uNDgtLjcyLDMuMzYsMy4zNiwwLDAsMC0zLC44OUgyNy4zMWExLDEsMCwwLDAtLjY4LjI4bC0uNTMuNTNIMjIuMjFhLjU0LjU0LDAsMCwwLS4zOC4xNmwtMy45NSwzLjk1YS41NC41NCwwLDAsMCwuMzguOTFoLjM2bDAsMEgyOS43MWMuNiw2LjI2LDEuNzUsMjIsMTYuNDIsMTcuMTlsLS4zMiw1TDQ0LjM3LDc4LjQ2YTEsMSwwLDAsMCwxLDFoNC45YTEsMSwwLDAsMCwxLTFsLS42MS0yMy4zMy0uMTUtNS44MWM2LTIuNzgsOS01LjY2LDE2LjE5LTYuNzUtMS41OSwyLjYyLTIuMDUsNi44Ny0yLjA2LDgtLjA2LDYsMi41NSw4Ljc0LDUsMTMuMjJMNjMuNzMsNzhhMSwxLDAsMCwwLC44OSwxLjMyaDQuNjRhMSwxLDAsMCwwLC45My0uNzRMNzQsNjIuNmMtNC44My03LjQzLDEuODMtMTUuMzEsMy40MS0xN0ExLDEsMCwwLDAsNzcuNjMsNDQuNzZaTTMxLDMxLjM2YTEuOTQsMS45NCwwLDAsMS0zLjYyLS44OS40My40MywwLDAsMSwuNTMtLjQ0LDMuMzIsMy4zMiwwLDAsMCwyLjgxLjdBLjQzLjQzLDAsMCwxLDMxLDMxLjM2WiIvPjxwYXRoIGNsYXNzPSJjbHMtNCIgZD0iTTQ2LjEzLDUxLjA3QzMxLjQ2LDU1LjkyLDMwLjMxLDQwLjE0LDI5LjcxLDMzLjg4SDE4LjY1TDIwLjc1LDM2YTEsMSwwLDAsMCwuNjguMjhoNmMwLDUuOCwxLjEzLDIwLjIsMTQsMjAuMmEzMS4zNCwzMS4zNCwwLDAsMCw0LjQyLS4zNVoiLz48cGF0aCBjbGFzcz0iY2xzLTQiIGQ9Ik01MC40MSw0OS4zNmwuMTUsNS44MWExMDguMiwxMDguMiwwLDAsMCwxNC00LjU0LDE5Ljc5LDE5Ljc5LDAsMCwxLDIuMDYtOEM1OS40Niw0My43LDU2LjQ0LDQ2LjU4LDUwLjQxLDQ5LjM2WiIvPjwvZz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - camel
  - integration
  - syndesis
  - fuse
  - online
  links:
  - name: Syndesis Project
    url: https://github.com/syndesisio/syndesis
  - name: Syndesis Operator
    url: https://github.com/syndesisio/syndesis/tree/master/install/operator
  maintainers:
  - email: syndesis@googlegroups.com
    name: Syndesis Team
  maturity: beta
  provider:
    name: Syndesis Team
    url: https://github.com/syndesisio/syndesis
  version: 1.12.0
